//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp9.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp9.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap default_car {
            get {
                object obj = ResourceManager.GetObject("default_car", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   태어난 일을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_BIRTH_DAY {
            get {
                return ResourceManager.GetString("ERR_BIRTH_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태어난 월을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_BIRTH_MONTH {
            get {
                return ResourceManager.GetString("ERR_BIRTH_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   태어난 연도를 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_BIRTH_YEAR {
            get {
                return ResourceManager.GetString("ERR_BIRTH_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   배기량 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_CAR_CC {
            get {
                return ResourceManager.GetString("ERR_CAR_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차량모델을 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_CAR_MODEL {
            get {
                return ResourceManager.GetString("ERR_CAR_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차량번호를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_CAR_NUMBER {
            get {
                return ResourceManager.GetString("ERR_CAR_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   차량연식을 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_CAR_YEAR {
            get {
                return ResourceManager.GetString("ERR_CAR_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_NAME {
            get {
                return ResourceManager.GetString("ERR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   담당자를 선택하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_STAFF_NAME {
            get {
                return ResourceManager.GetString("ERR_STAFF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전화번호 뒷자리 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_TEL_B {
            get {
                return ResourceManager.GetString("ERR_TEL_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전화번호 앞자리 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERR_TEL_H {
            get {
                return ResourceManager.GetString("ERR_TEL_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap K3 {
            get {
                object obj = ResourceManager.GetObject("K3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MainImg {
            get {
                object obj = ResourceManager.GetObject("MainImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 그랜저 {
            get {
                object obj = ResourceManager.GetObject("그랜저", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 소나타 {
            get {
                object obj = ResourceManager.GetObject("소나타", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 아반떼 {
            get {
                object obj = ResourceManager.GetObject("아반떼", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 아이오닉 {
            get {
                object obj = ResourceManager.GetObject("아이오닉", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap 제네시스 {
            get {
                object obj = ResourceManager.GetObject("제네시스", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
